export const projects = [
  {
    title: 'Day 1',
    description: "Repository with All Chalenge Projects.",
      image: '/images/day1.png',
      tags: ['Git' , 'Github'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Day 2',
    description:"Custom a Hello World.",
    image: '/images/hello1.png',
    tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Day 3',
    description: "Animated button.",
      image: '/images/button1.png',
      tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Day 4',
    description: "Calculator.",
    image: '/images/calculator.png',
    tags: ['React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Day 5',
    description: "Custom a 404 Error Page.",
      image: '/images/error.png',
      tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Day 6',
    description: "Card with Glassmorphism Effect.",
      image: '/images/card.png',
      tags: ['HTML', 'CSS','Vanilla'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'Day 7',
    description: "Create a counter.",
      image: '/images/counter.png',
      tags: ['React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 6,
  },
  {
    title: 'Day 8',
    description: "Develop a toggle that changes the light theme to dark.",
      image: '/images/darlt.png',
      tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 7,
  },
  {
    title: 'Day 9',
    description: "Create a loading animation.",
      image: '/images/load.png',
      tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 8,
  },
  {
    title: 'Day 10',
    description: "Use the javaScript Particle.js lib.",
      image: '/images/partic.png',
      tags: ['HTML', 'Vanilla', 'API'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 9,
  },
  {
    title: 'Day 11',
    description: "Create a login form layout.",
      image: '/images/login.png',
      tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 10,
  },
  {
    title: 'Day 12',
    description: "Develop an image gallery.",
      image: '/images/galler.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 11,
  },
  {
    title: 'Day 13',
    description: "Develop a responsive menu.",
      image: '/images/menu.png',
      tags: ['React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 12,
  },
  {
    title: 'Day 14',
    description: "Create a quiz form.",
      image: '/images/quiz.png',
      tags: ['React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 13,
  },
  {
    title: 'Day 15',
    description: "Develop a website that displays a showcase of fictitious e-commerce products, with names, prices, and images.",
      image: '/images/ecommer.png',
      tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 14,
  },
  {
    title: 'Day 16',
    description: "Develop a website by creating a public API.",
      image: '/images/api.png',
      tags: ['React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 15,
  },
  {
    title: 'Day 17',
    description: "Develop a website that captures keyboard events and displays the event and key pressed on the screen.",
      image: '/images/key.png',
      tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 16,
  },
  {
    title: 'Day 18',
    description: "Develop a random password generator.",
      image: '/images/pass.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 17,
  },
  {
    title: 'Day 19',
    description: "Develop a website that generates random images using the unsplash API.",
      image: '/images/random.png',
      tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 18,
  },
  {
    title: 'Day 20',
    description: "Develop an emoji picker website, when selecting the emoji it is copied to the clipboard.",
      image: '/images/emmoji.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 19,
  },
  {
    title: 'Day 21',
    description: "Develop a page for your portfolio with all challenges.",
      image: '/images/port.png',
      tags: ['Nextjs', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 20,
  }
];